# Generated by Django 6.0.1 on 2026-01-28 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoVaciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('cantidad_periodos', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleF29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('ingresos', models.IntegerField(default=0)),
                ('compras_netas', models.IntegerField(default=0)),
                ('compras_exentas', models.IntegerField(default=0)),
                ('boletas_honorarios', models.IntegerField(default=0)),
                ('ppm', models.IntegerField(default=0)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.procesovaciado')),
            ],
        ),
    ]
